#!/bin/sh

echo ""
echo "Checkm4te! ♕"
echo ""
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo "▀▄▀▄▀▄▀▄"
echo ""
echo "Thank You For Installing Matoi v1.0.0"
echo ""
echo "Created by AppleWorm ♤"
